### ISSUE TITLE
handheld shader didnt show the proper screen shader

### ISSUE THREAD

**Issue by oilbugxx** [Duimon/Duimon-Mega-Bezel-Potato#1]
i dont know if i should post this here, since it seems like no one submit any issue before. 
so, the issue that ive encountered was that handheld shader, tobe precise gba and gba sp doesnt show the proper screen shader that the name referring to. it should be lcd shader, but i cant figure out how to turn off the crt guest shader nor to switch to lcd shader.

it just doesnt feel right to play gba games with gba handheld overlay but with scanline on it.

but, thankyou for your work, i adore this alot, it really enhanced my playthrough. and also the dynamic overscan crop just awesome. i dont know why cant other shader implement this feature, that thing bothers me alot. but i guess thats mega bezel for you then.

**Comment by Duimon** [comment]
This is the GBA SP.

![Rayman Advance-231020-161614](https://github.com/Duimon/Duimon-Mega-Bezel-Potato/assets/64669031/380d52e3-37a1-4ffe-9fd4-f0cd09d3064d)

That is the LCD-GRID shader, as the name says.

There is also a GBA "Bezel" preset that uses the guest CRT shader, but I just checked and the GBA presets that say LCD-GRID do indeed all use the LCD-GRID base preset.

**Comment by Duimon** [comment]
I just noticed you were referring to the Potato presets. It looks like the Mega Bezel Base preset they use

`MBZ__5__POTATO__LCD-GRID.slangp` 

is actually not the LCD shader. This is a bug in the Mega Bezel, not my presets, so HSM will have to fix it. I honestly don't think it is something he will fix sooner than later because of where he is in development right now.

I took a look it appears that the file. . . `\shaders\shaders_slang\bezel\Mega_Bezel\shaders\lcd-cgwg\hsm-lcd-grid-v2-potato.slang`

is referencing the wrong include.

```
#version 450

#include "../base/common/globals-and-potato-params.inc"
#include "../base/common/common-functions.inc"
#include "../guest/hsm-crt-guest-advanced.inc"
```

the last line should read. . .

```#include "hsm-lcd-grid-v2.inc"```

Editing this file should solve your issue until HSM does a new release.

**Comment by oilbugxx** [comment]
ah, thats the problem. thank you, ill try it later then.
